const GITHUB_PERSONAL_ACCESS_TOKEN = "YOUR TOKEN";
const DEFAULT_SEARCH_VALUE = "mui";
const DEFAULT_RESULTS_COUNT = 10;
const EXCESSIVE_PAGINATION = 100;
const SHOW_MORE_BUTTON_TEXT = "Show more";
const SOMETHING_WENT_WRONG_MESSAGE = "Noop! ;)";

export {
  GITHUB_PERSONAL_ACCESS_TOKEN,
  DEFAULT_SEARCH_VALUE,
  DEFAULT_RESULTS_COUNT,
  EXCESSIVE_PAGINATION,
  SOMETHING_WENT_WRONG_MESSAGE,
  SHOW_MORE_BUTTON_TEXT,
};
